[package]
name = "pebble"
version = "0.1.0"
authors = ["BooleanCat <thgodkin@gmail.com>"]
edition = "2018"

[lib]
name = "libpebble"
path = "src/lib.rs"

[[bin]]
name = "pebble"
path = "src/bin.rs"

[dependencies]
structopt = {version = "0.3"}
libc = {version = "0.2"}
