[package]
name = "pebble"
version = "0.1.0"
authors = ["BooleanCat <thgodkin@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
structopt = "0.3"
serde_json = "1.0"
libpebble = { path = "../libpebble" }
uuid = { version = "0.8", features = ["v4"]}