[package]
name = "libpebble"
version = "0.1.0"
authors = ["BooleanCat <thgodkin@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"